Listen 443

<VirtualHost *:443>
    ServerName casopractico2.local
    DocumentRoot "/usr/local/apache2/htdocs"

    SSLEngine on
    SSLCertificateFile      "/usr/local/apache2/conf/ssl/cert.pem"
    SSLCertificateKeyFile   "/usr/local/apache2/conf/ssl/key.pem"

    <Directory "/usr/local/apache2/htdocs">
        AuthType Basic
        AuthName "Caso Practico 2 - Acceso restringido"
        AuthUserFile "/usr/local/apache2/conf/ssl/.htpasswd"
        Require valid-user
    </Directory>
</VirtualHost>